### ISSUE TITLE
bug in IRI regex - hyphens not allowed

### ISSUE THREAD

**Issue by paulwilton** [eddieantonio/node-sparql-client#8]
I think there is  a bug in iri.js , the regex on line 90 doesn't allow hyphen chars
for example this URI 
`http://domain.com/test-hyphen`
fails the IRI check
i think the regex is too restrictive for the IRI spec

**Comment by paulwilton** [comment]
the IRI spec (RFC 3987) is much more complex, there is an RFC 3987 compliant regex here: http://stackoverflow.com/a/190405

**Comment by eddieantonio** [comment]
Hey @paulwilton,

Thanks for the issue. A link to the IRI regex is very helpful! I'm checking it out.

**Comment by paulwilton** [comment]
cool :)  nice library by the way - 
its not a trivial thing building a regex for a URI let alone an IRI - the one above is claimed to be fully compliant , but is a monster.

**Comment by eddieantonio** [comment]
One final update: this is fix is now incorporated in v0.6.1.

**Comment by paulwilton** [comment]
Great thanks for fixing this so quickly @eddieantonio
